### ISSUE TITLE
Failed to bind properties under 'spring.datasource.password' to java.lang.String

### ISSUE THREAD

**Issue by dolcevitaforever** [ulisesbocchio/jasypt-spring-boot#128] opened 2019-05-14 05:49 UTC
hi，my project 
Use 2.1.1 for(jasypt-spring-boot-starter)，Spring Boot Version: 2.1.2.RELEASE
and has used @SpringBootApplication.  JDK8
my config file content is 
spring.datasource.username=root
spring.datasource.password=ENC(o6tc7zDeH66nmMOQwWalge445Or4Kl3l7bAmjs9y7GI=)

but i have got the exception:
2019-05-14 13:43:26.608 [main] ERROR o.s.boot.web.embedded.tomcat.TomcatStarter -
				Error starting Tomcat context. Exception: org.springframework.beans.factory.BeanCreationException. Message: Error creating bean with name 'servletEndpointRegistrar' defined in class path resource [org/springframework/boot/actuate/autoconfigure/endpoint/web/ServletEndpointManagementContextConfiguration$WebMvcServletEndpointManagementContextConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.endpoint.web.ServletEndpointRegistrar]: Factory method 'servletEndpointRegistrar' threw exception; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'healthEndpoint' defined in class path resource [org/springframework/boot/actuate/autoconfigure/health/HealthEndpointConfiguration.class]: Unsatisfied dependency expressed through method 'healthEndpoint' parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'healthIndicatorRegistry' defined in class path resource [org/springframework/boot/actuate/autoconfigure/health/HealthIndicatorAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.health.HealthIndicatorRegistry]: Factory method 'healthIndicatorRegistry' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.actuate.autoconfigure.jdbc.DataSourceHealthIndicatorAutoConfiguration': Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.autoconfigure.jdbc.DataSourceHealthIndicatorAutoConfiguration$$EnhancerBySpringCGLIB$$7b4b82bd]: Constructor threw exception; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'dataSource': Unsatisfied dependency expressed through field 'basicProperties'; nested exception is org.springframework.boot.context.properties.ConfigurationPropertiesBindException: Error creating bean with name 'spring.datasource-org.springframework.boot.autoconfigure.jdbc.DataSourceProperties': Could not bind properties to 'DataSourceProperties' : prefix=spring.datasource, ignoreInvalidFields=false, ignoreUnknownFields=true; nested exception is org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'spring.datasource.password' to java.lang.String
2019-05-14 13:43:26.641 [main] INFO  org.apache.catalina.core.StandardService -
				Stopping service [Tomcat]
2019-05-14 13:43:26.669 [main] WARN  o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext -
				Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat
2019-05-14 13:43:26.679 [main] INFO  o.s.b.a.l.ConditionEvaluationReportLoggingListener -
				

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2019-05-14 13:43:26.681 [main] ERROR o.s.b.diagnostics.LoggingFailureAnalysisReporter -
				

***************************
APPLICATION FAILED TO START
***************************

why? waiting for your answer, thanks.

**Comment by anderius** [comment] 2019-06-19 11:55
For security reasons, the actual exception is masked.

You will probably find the answer by debugging `org.jasypt.encryption.pbe.StandardPBEByteEncryptor#decrypt` (or whatever Encryptor you use).

**Comment by DavidWhom** [comment] 2019-07-09 14:38
@dolcevitaforever I got this exception too. How do u slove this problem later. Can u help me .. thank u

**Comment by crazythinking** [comment] 2019-07-31 07:43
root cause:
if you debug into org.jasypt.encryption.pbe.StandardPBEByteEncryptor#decrypt, you will find the real exception is "javax.crypto.BadPaddingException: Given final block not properly padded"; that cause you maybe generate encryptor by "com.melloware.jasypt 1.9.4", so you need use "org.jasypt.jasypt 1.9.3"

**Comment by ulisesbocchio** [comment] 2019-09-08 02:33
next release will go back to jasypt 1.9.3 and this should be fixed

**Closed by ulisesbocchio** 2019-09-08 02:33 UTC
